server:
  servlet:
    context-path: /app-api
  port: 3000

spring:
  application:
    name: example
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  # 扫描实体类，类型别名
  type-aliases-package: com.example.entity
  # 扫描mapper文件
  mapper-locations: classpath:mapper/*.xml

  configuration:
    # 日志输出
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 数据库中的下划线转成驼峰
    map-underscore-to-camel-case: true
